<?php

use App\Concert;
use Illuminate\Database\Seeder;

class ConcertsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Concert::create([
            'venue' => 'Nottingham Arena',
            'city' => 'Nottingham',
            'country' => 'UK',
            'date' => '2003-11-29'
        ])->addSongs([
            '2 + 2 = 5',
            'Sit down. Stand up',
            'Morning Bell',
            'Where I End and You Begin',
            'Kid A',
            'Backdrifts',
            'I Will',
            'The National Anthem',
            'A Wolf at the Door',
            'Paranoid Android',
            'Scatterbrain',
            'Airbag',
            'Climbing Up the Walls',
            'Pyramid Song',
            'Idioteque',
            'The Gloaming',
            'There There',
            'Encore',
            'Sail to the Moon',
            'Just',
            'A Punchup at a Wedding',
            'Street Spirit (Fade Out)',
            'Encore',
            'You and Whose Army?',
            'The Bends',
            'Fog',
            'Everything in Its Right Place',
        ]);

        Concert::create([
            'venue' => 'Heineken Music Hall',
            'city' =>  'Amsterdam',
            'country' => 'Netherlands',
            'date' => '2006-05-09'
        ])->addSongs([
            'Everything in Its Right Place',
            'The National Anthem',
            '15 Step',
            'Lucky',
            '2 + 2 = 5',
            'Bangers + Mash',
            'Nude',
            'Pyramid Song',
            'Jigsaw Falling into Place',
            'I Might Be Wrong',
            'Paranoid Android',
            'How to Disappear Completely',
            'Karma Police',
            'Bodysnatchers',
            'Idioteque',
            'No Surprises',
            'There There',
            'Encore',
            'Spooks',
            'House of Cards',
            'Just',
            'You and Whose Army?',
            'Encore',
            'Street Spirit (Fade Out)',
        ]);

        Concert::create([
            'venue' => 'Rock en Seine',
            'city' =>  'Paris',
            'country' => 'France',
            'date' => '2006-08-26'
        ])->addSongs([
            'Airbag',
            '2 + 2 = 5',
            'The National Anthem',
            'My Iron Lung',
            'Morning Bell',
            'Fake Plastic Trees',
            'Videotape',
            'Nude',
            'The Gloaming',
            'Paranoid Android',
            'All I Need',
            'Pyramid Song',
            'Lucky',
            'The Bends',
            'I Might Be Wrong',
            'Idioteque',
            'Everything in Its Right Place',
            'Encore',
            'You and Whose Army?',
            'Bodysnatchers',
            'There There',
            'Karma Police',
        ]);

        Concert::create([
            'venue' => '93 Feet East',
            'city' =>  'London',
            'country' => 'UK',
            'date' => '2008-01-16'
        ])->addSongs([
            '15 Step',
            'Bodysnatchers',
            'Nude',
            'Weird Fishes/Arpeggi',
            'All I Need',
            'Faust Arp',
            'Reckoner',
            'House of Cards',
            'Jigsaw Falling into Place',
            'Videotape',
            'Encore',
            'Up on the Ladder',
            'You and Whose Army?',
            'The National Anthem',
            'My Iron Lung',
            'The Bends',
        ]);

        Concert::create([
            'venue' => 'Victoria Park',
            'city' =>  'London',
            'country' => 'UK',
            'date' => '2008-06-24'
        ])->addSongs([
            '15 Step',
            'Bodysnatchers',
            'All I Need',
            'The National Anthem',
            'Pyramid Song',
            'Nude',
            'Weird Fishes/Arpeggi',
            'The Gloaming',
            'Dollars and Cents',
            'Faust Arp',
            'There There',
            'Just',
            'Climbing Up the Walls',
            'Reckoner',
            'Everything in Its Right Place',
            'How to Disappear Completely',
            'Jigsaw Falling into Place',
            'Encore',
            'Videotape',
            'Airbag',
            'Bangers + Mash',
            'Planet Telex',
            'The Tourist',
            'Encore',
            'Cymbal Rush',
            'You and Whose Army?',
            'Idioteque',
        ]);

        Concert::create([
            'venue' => 'Victoria Park',
            'city' =>  'London',
            'country' => 'UK',
            'date' => '2008-06-25'
        ])->addSongs([
            'Reckoner',
            '15 Step',
            'There There',
            'All I Need',
            'Lucky',
            'Nude',
            'Weird Fishes/Arpeggi',
            'Myxomatosis',
            'The National Anthem',
            'Faust Arp',
            'No Surprises',
            'Jigsaw Falling into Place',
            'Optimistic',
            'Videotape',
            'Everything in Its Right Place',
            'Idioteque',
            'Bodysnatchers',
            'Encore',
            'House of Cards',
            'The Bends',
            'Bangers + Mash',
            'My Iron Lung',
            'Karma Police',
            'Encore',
            'Go Slowly',
            '2 + 2 = 5',
            'Paranoid Android',
        ]);

        Concert::create([
            'venue' => 'Santa Barbara Bowl',
            'city' =>  'Santa Barbara, CA',
            'country' => 'USA',
            'date' => '2008-08-28'
        ])->addSongs([
            'Reckoner',
            'Optimistic',
            'There There',
            '15 Step',
            'All I Need',
            'Nude',
            'Talk Show Host',
            'Weird Fishes/Arpeggi',
            'The Gloaming',
            'Morning Bell',
            'The National Anthem',
            'Faust Arp',
            'No Surprises',
            'Jigsaw Falling into Place',
            'The Bends',
            'Karma Police',
            'Bodysnatchers',
            'Encore',
            'Cymbal Rush',
            'House of Cards',
            'Paranoid Android',
            'Go Slowly',
            'Everything in Its Right Place',
            'Encore',
            'Videotape',
            'Lucky',
            'Idioteque',
        ]);

        Concert::create([
            'venue' => 'American Airlines Center',
            'city' =>  'Dallas, TX',
            'country' => 'USA',
            'date' => '2012-03-05'
        ])->addSongs([
            'Bloom',
            'Little by Little',
            'Weird Fishes/Arpeggi',
            'Morning Mr Magpie',
            'The Gloaming',
            'The Daily Mail',
            'Pyramid Song',
            'The Amazing Sounds of Orgy',
            'Karma Police',
            '15 Step',
            'Staircase',
            'Identikit',
            'Lotus Flower',
            'There There',
            'Feral',
            'Idioteque',
            'Encore',
            'Separator',
            'Climbing Up the Walls',
            'Bodysnatchers',
            'Everything in Its Right Place',
            'Encore',
            'Give Up the Ghost',
            'Skirting on the Surface',
            'Reckoner',
            'Paranoid Android',
        ]);

        Concert::create([
            'venue' => 'ACL (Zilker Park)',
            'city' =>  'Austin, TX',
            'country' => 'USA',
            'date' => '2016-09-30'
        ])->addSongs([
            'Burn the Witch',
            'Daydreaming',
            'Ful Stop',
            'Airbag',
            '2 + 2 = 5',
            'The National Anthem',
            'Bloom',
            'Lotus Flower',
            'The Gloaming',
            'Exit Music (For a Film)',
            'The Numbers',
            'Identikit',
            'Reckoner',
            'Everything in Its Right Place',
            'Idioteque',
            'Bodysnatchers',
            'Street Spirit (Fade Out)',
            'Encore',
            'Give Up the Ghost',
            'Paranoid Android',
            'Nude',
            'Weird Fishes/Arpeggi',
            'There There',
            'Karma Police',
        ]);
    }
}
