<?php

use App\Concert;
use Illuminate\Database\Seeder;

class ConcertsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Concert::create([
            'venue' => 'Nottingham Arena',
            'city' => 'Nottingham',
            'country' => 'UK',
            'date' => '2003-11-29',
            'attendees' => 'Sturart, Bruce and Yolande',
            'description' => 'Are you such a dreamer... So after many years of listening to Radiohead in my bedroom, I finally attend my first concert. I was living in Nottingham at the time hence the venue. I remember lots of jumping up and down during the first song before it settled down somewhat. "There There" was spectacular live.',
        ])->addSongs([
            '2 + 2 = 5',
            'Sit down. Stand up',
            'Morning Bell',
            'Where I End and You Begin',
            'Kid A',
            'Backdrifts',
            'I Will',
            'The National Anthem',
            'A Wolf at the Door',
            'Paranoid Android',
            'Scatterbrain',
            'Airbag',
            'Climbing Up the Walls',
            'Pyramid Song',
            'Idioteque',
            'The Gloaming',
            'There There',
            'Encore',
            'Sail to the Moon',
            'Just',
            'A Punchup at a Wedding',
            'Street Spirit (Fade Out)',
            'Encore',
            'You and Whose Army?',
            'The Bends',
            'Fog',
            'Everything in Its Right Place',
        ]);

        Concert::create([
            'venue' => 'Heineken Music Hall',
            'city' =>  'Amsterdam',
            'country' => 'Netherlands',
            'date' => '2006-05-09',
            'attendees' => 'Hendrik',
            'description' => 'The last leg of my mini Euro-tour was a stop in Amsterdam to see Radiohead. I remember very early on they played "Lucky" and it sounded absolutely amazing. After the encore they played a new song called "Spooks" which I remember as short and full of energy. I loved it. This was my favourite Radiohead concert.',
        ])->addSongs([
            'Everything in Its Right Place',
            'The National Anthem',
            '15 Step',
            'Lucky',
            '2 + 2 = 5',
            'Bangers + Mash',
            'Nude',
            'Pyramid Song',
            'Jigsaw Falling into Place',
            'I Might Be Wrong',
            'Paranoid Android',
            'How to Disappear Completely',
            'Karma Police',
            'Bodysnatchers',
            'Idioteque',
            'No Surprises',
            'There There',
            'Encore',
            'Spooks',
            'House of Cards',
            'Just',
            'You and Whose Army?',
            'Encore',
            'Street Spirit (Fade Out)',
        ]);

        Concert::create([
            'venue' => 'Rock en Seine',
            'city' =>  'Paris',
            'country' => 'France',
            'date' => '2006-08-26',
            'attendees' => 'Delphine and Adrien',
            'description' => 'Summer 2006 and I\'m in Paris for the "Rock en Seine" music festival. I specifically remember hearing "Videotape" for the first time. It was unreleased at the time and I took an audio recording of it on my camera.',
        ])->addSongs([
            'Airbag',
            '2 + 2 = 5',
            'The National Anthem',
            'My Iron Lung',
            'Morning Bell',
            'Fake Plastic Trees',
            'Videotape',
            'Nude',
            'The Gloaming',
            'Paranoid Android',
            'All I Need',
            'Pyramid Song',
            'Lucky',
            'The Bends',
            'I Might Be Wrong',
            'Idioteque',
            'Everything in Its Right Place',
            'Encore',
            'You and Whose Army?',
            'Bodysnatchers',
            'There There',
            'Karma Police',
        ]);

        Concert::create([
            'venue' => '93 Feet East',
            'city' =>  'London',
            'country' => 'UK',
            'date' => '2008-01-16',
            'attendees' => '3 random people',
            'description' => 'Early that morning I spotted a message on Facebook that Radiohead would be performing a secret gig in the east end of London where I lived. I called work, told then I wasn\'t coming in, and joined the queue. Eight hours later the door opened and I got to see Radiohead perform the entire "In Rainbows" album to a small crowd of 200 people.',
        ])->addSongs([
            '15 Step',
            'Bodysnatchers',
            'Nude',
            'Weird Fishes/Arpeggi',
            'All I Need',
            'Faust Arp',
            'Reckoner',
            'House of Cards',
            'Jigsaw Falling into Place',
            'Videotape',
            'Encore',
            'Up on the Ladder',
            'You and Whose Army?',
            'The National Anthem',
            'My Iron Lung',
            'The Bends',
        ]);

        Concert::create([
            'venue' => 'Victoria Park',
            'city' =>  'London',
            'country' => 'UK',
            'date' => '2008-06-24',
            'attendees' => 'Simon and Gary',
            'description' => 'A dream come true as Radiohead play back to back concerts in Victoria Park, my local park, just 5 minutes walk from my house. Again "There There" was amazing and I heard "Planet Telex" and "The Tourist" for the first time. A treat after the second encore as Thom played "Cymbal Rush".',
        ])->addSongs([
            '15 Step',
            'Bodysnatchers',
            'All I Need',
            'The National Anthem',
            'Pyramid Song',
            'Nude',
            'Weird Fishes/Arpeggi',
            'The Gloaming',
            'Dollars and Cents',
            'Faust Arp',
            'There There',
            'Just',
            'Climbing Up the Walls',
            'Reckoner',
            'Everything in Its Right Place',
            'How to Disappear Completely',
            'Jigsaw Falling into Place',
            'Encore',
            'Videotape',
            'Airbag',
            'Bangers + Mash',
            'Planet Telex',
            'The Tourist',
            'Encore',
            'Cymbal Rush',
            'You and Whose Army?',
            'Idioteque',
        ]);

        Concert::create([
            'venue' => 'Victoria Park',
            'city' =>  'London',
            'country' => 'UK',
            'date' => '2008-06-25',
            'attendees' => 'Tom and Michelle',
            'description' => 'Night two at Victoria Park. A similar set to night one but still some songs I havn\'t heard live before including "Myxomatosis" and "Optimistic". By this stage I am able to recognise which song are coming next based on which guitar Thom picked up.',
        ])->addSongs([
            'Reckoner',
            '15 Step',
            'There There',
            'All I Need',
            'Lucky',
            'Nude',
            'Weird Fishes/Arpeggi',
            'Myxomatosis',
            'The National Anthem',
            'Faust Arp',
            'No Surprises',
            'Jigsaw Falling into Place',
            'Optimistic',
            'Videotape',
            'Everything in Its Right Place',
            'Idioteque',
            'Bodysnatchers',
            'Encore',
            'House of Cards',
            'The Bends',
            'Bangers + Mash',
            'My Iron Lung',
            'Karma Police',
            'Encore',
            'Go Slowly',
            '2 + 2 = 5',
            'Paranoid Android',
        ]);

        Concert::create([
            'venue' => 'Santa Barbara Bowl',
            'city' =>  'Santa Barbara, CA',
            'country' => 'USA',
            'date' => '2008-08-28',
            'attendees' => 'Jillian, Miriam and Kelly',
            'description' => 'One of the highlights of my 2008 California trip was a visit to the Santa Barbara Bowl to see Radiohead. We drove from Los Angeles in the morning and headed up north after the concert to San Francisco. The band plays "Talk Show Host", a b-side I get to hear for the first time.',
        ])->addSongs([
            'Reckoner',
            'Optimistic',
            'There There',
            '15 Step',
            'All I Need',
            'Nude',
            'Talk Show Host',
            'Weird Fishes/Arpeggi',
            'The Gloaming',
            'Morning Bell',
            'The National Anthem',
            'Faust Arp',
            'No Surprises',
            'Jigsaw Falling into Place',
            'The Bends',
            'Karma Police',
            'Bodysnatchers',
            'Encore',
            'Cymbal Rush',
            'House of Cards',
            'Paranoid Android',
            'Go Slowly',
            'Everything in Its Right Place',
            'Encore',
            'Videotape',
            'Lucky',
            'Idioteque',
        ]);

        Concert::create([
            'venue' => 'American Airlines Center',
            'city' =>  'Dallas, TX',
            'country' => 'USA',
            'date' => '2012-03-05',
            'attendees' => 'Jillian',
            'description' => 'By 2012, I was living in America. On Radiohead\'s next US tour, we went to our local concert in Dallas. The band plays "The Amazing Sounds of Orgy" for the very first time live, a b-side from 2001.',
        ])->addSongs([
            'Bloom',
            'Little by Little',
            'Weird Fishes/Arpeggi',
            'Morning Mr Magpie',
            'The Gloaming',
            'The Daily Mail',
            'Pyramid Song',
            'The Amazing Sounds of Orgy',
            'Karma Police',
            '15 Step',
            'Staircase',
            'Identikit',
            'Lotus Flower',
            'There There',
            'Feral',
            'Idioteque',
            'Encore',
            'Separator',
            'Climbing Up the Walls',
            'Bodysnatchers',
            'Everything in Its Right Place',
            'Encore',
            'Give Up the Ghost',
            'Skirting on the Surface',
            'Reckoner',
            'Paranoid Android',
        ]);

        Concert::create([
            'venue' => 'ACL (Zilker Park)',
            'city' =>  'Austin, TX',
            'country' => 'USA',
            'date' => '2016-09-30',
            'attendees' => 'Jillian, Lissa and Ryan',
            'description' => 'Summer 2016 as we drive down to Austin for the "Austin City Limits" music festival. The new "Moon Shaped Pool" songs sound great and I hear "Exit Music" for the first time. The set ends with "Karma Police" and the crowd joins Thom for a sing-along. For a minute there...',
        ])->addSongs([
            'Burn the Witch',
            'Daydreaming',
            'Ful Stop',
            'Airbag',
            '2 + 2 = 5',
            'The National Anthem',
            'Bloom',
            'Lotus Flower',
            'The Gloaming',
            'Exit Music (For a Film)',
            'The Numbers',
            'Identikit',
            'Reckoner',
            'Everything in Its Right Place',
            'Idioteque',
            'Bodysnatchers',
            'Street Spirit (Fade Out)',
            'Encore',
            'Give Up the Ghost',
            'Paranoid Android',
            'Nude',
            'Weird Fishes/Arpeggi',
            'There There',
            'Karma Police',
        ]);
    }
}
